// Code generated by mockery v2.33.2. DO NOT EDIT.

package fsm

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockContext is an autogenerated mock type for the Context type
type MockContext struct {
	mock.Mock
}

type MockContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContext) EXPECT() *MockContext_Expecter {
	return &MockContext_Expecter{mock: &_m.Mock}
}

// Data provides a mock function with given fields: ctx, key, to
func (_m *MockContext) Data(ctx context.Context, key string, to interface{}) error {
	ret := _m.Called(ctx, key, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockContext_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - to interface{}
func (_e *MockContext_Expecter) Data(ctx interface{}, key interface{}, to interface{}) *MockContext_Data_Call {
	return &MockContext_Data_Call{Call: _e.mock.On("Data", ctx, key, to)}
}

func (_c *MockContext_Data_Call) Run(run func(ctx context.Context, key string, to interface{})) *MockContext_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockContext_Data_Call) Return(_a0 error) *MockContext_Data_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Data_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockContext_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function with given fields: ctx, deleteData
func (_m *MockContext) Finish(ctx context.Context, deleteData bool) error {
	ret := _m.Called(ctx, deleteData)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, deleteData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockContext_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - deleteData bool
func (_e *MockContext_Expecter) Finish(ctx interface{}, deleteData interface{}) *MockContext_Finish_Call {
	return &MockContext_Finish_Call{Call: _e.mock.On("Finish", ctx, deleteData)}
}

func (_c *MockContext_Finish_Call) Run(run func(ctx context.Context, deleteData bool)) *MockContext_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockContext_Finish_Call) Return(_a0 error) *MockContext_Finish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Finish_Call) RunAndReturn(run func(context.Context, bool) error) *MockContext_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// MustGet provides a mock function with given fields: ctx, key, to
func (_m *MockContext) MustGet(ctx context.Context, key string, to interface{}) {
	_m.Called(ctx, key, to)
}

// MockContext_MustGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustGet'
type MockContext_MustGet_Call struct {
	*mock.Call
}

// MustGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - to interface{}
func (_e *MockContext_Expecter) MustGet(ctx interface{}, key interface{}, to interface{}) *MockContext_MustGet_Call {
	return &MockContext_MustGet_Call{Call: _e.mock.On("MustGet", ctx, key, to)}
}

func (_c *MockContext_MustGet_Call) Run(run func(ctx context.Context, key string, to interface{})) *MockContext_MustGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockContext_MustGet_Call) Return() *MockContext_MustGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_MustGet_Call) RunAndReturn(run func(context.Context, string, interface{})) *MockContext_MustGet_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function with given fields: ctx, state
func (_m *MockContext) SetState(ctx context.Context, state State) error {
	ret := _m.Called(ctx, state)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, State) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockContext_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx context.Context
//   - state State
func (_e *MockContext_Expecter) SetState(ctx interface{}, state interface{}) *MockContext_SetState_Call {
	return &MockContext_SetState_Call{Call: _e.mock.On("SetState", ctx, state)}
}

func (_c *MockContext_SetState_Call) Run(run func(ctx context.Context, state State)) *MockContext_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(State))
	})
	return _c
}

func (_c *MockContext_SetState_Call) Return(_a0 error) *MockContext_SetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_SetState_Call) RunAndReturn(run func(context.Context, State) error) *MockContext_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with given fields: ctx
func (_m *MockContext) State(ctx context.Context) (State, error) {
	ret := _m.Called(ctx)

	var r0 State
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (State, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) State); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(State)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContext_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockContext_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContext_Expecter) State(ctx interface{}) *MockContext_State_Call {
	return &MockContext_State_Call{Call: _e.mock.On("State", ctx)}
}

func (_c *MockContext_State_Call) Run(run func(ctx context.Context)) *MockContext_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContext_State_Call) Return(_a0 State, _a1 error) *MockContext_State_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContext_State_Call) RunAndReturn(run func(context.Context) (State, error)) *MockContext_State_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, key, data
func (_m *MockContext) Update(ctx context.Context, key string, data interface{}) error {
	ret := _m.Called(ctx, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContext_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data interface{}
func (_e *MockContext_Expecter) Update(ctx interface{}, key interface{}, data interface{}) *MockContext_Update_Call {
	return &MockContext_Update_Call{Call: _e.mock.On("Update", ctx, key, data)}
}

func (_c *MockContext_Update_Call) Run(run func(ctx context.Context, key string, data interface{})) *MockContext_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockContext_Update_Call) Return(_a0 error) *MockContext_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Update_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockContext_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContext creates a new instance of MockContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContext {
	mock := &MockContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
